//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsSOAP.SOAPService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/WcfBiblioteca")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BorradoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DniField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Borrado {
            get {
                return this.BorradoField;
            }
            set {
                if ((this.BorradoField.Equals(value) != true)) {
                    this.BorradoField = value;
                    this.RaisePropertyChanged("Borrado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodUsuario {
            get {
                return this.CodUsuarioField;
            }
            set {
                if ((this.CodUsuarioField.Equals(value) != true)) {
                    this.CodUsuarioField = value;
                    this.RaisePropertyChanged("CodUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dni {
            get {
                return this.DniField;
            }
            set {
                if ((object.ReferenceEquals(this.DniField, value) != true)) {
                    this.DniField = value;
                    this.RaisePropertyChanged("Dni");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FNacimiento {
            get {
                return this.FNacimientoField;
            }
            set {
                if ((this.FNacimientoField.Equals(value) != true)) {
                    this.FNacimientoField = value;
                    this.RaisePropertyChanged("FNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Passwd {
            get {
                return this.PasswdField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswdField, value) != true)) {
                    this.PasswdField = value;
                    this.RaisePropertyChanged("Passwd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SOAPService.IUsuario")]
    public interface IUsuario {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/GetVersion", ReplyAction="http://tempuri.org/IUsuario/GetVersionResponse")]
        string GetVersion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/GetVersion", ReplyAction="http://tempuri.org/IUsuario/GetVersionResponse")]
        System.Threading.Tasks.Task<string> GetVersionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/getUsuarioById", ReplyAction="http://tempuri.org/IUsuario/getUsuarioByIdResponse")]
        WsSOAP.SOAPService.Usuario getUsuarioById(int codUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/getUsuarioById", ReplyAction="http://tempuri.org/IUsuario/getUsuarioByIdResponse")]
        System.Threading.Tasks.Task<WsSOAP.SOAPService.Usuario> getUsuarioByIdAsync(int codUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/getAll", ReplyAction="http://tempuri.org/IUsuario/getAllResponse")]
        WsSOAP.SOAPService.Usuario[] getAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/getAll", ReplyAction="http://tempuri.org/IUsuario/getAllResponse")]
        System.Threading.Tasks.Task<WsSOAP.SOAPService.Usuario[]> getAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/getAllNoBorrados", ReplyAction="http://tempuri.org/IUsuario/getAllNoBorradosResponse")]
        WsSOAP.SOAPService.Usuario[] getAllNoBorrados();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/getAllNoBorrados", ReplyAction="http://tempuri.org/IUsuario/getAllNoBorradosResponse")]
        System.Threading.Tasks.Task<WsSOAP.SOAPService.Usuario[]> getAllNoBorradosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/getAllBorrados", ReplyAction="http://tempuri.org/IUsuario/getAllBorradosResponse")]
        WsSOAP.SOAPService.Usuario[] getAllBorrados();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/getAllBorrados", ReplyAction="http://tempuri.org/IUsuario/getAllBorradosResponse")]
        System.Threading.Tasks.Task<WsSOAP.SOAPService.Usuario[]> getAllBorradosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/getByUsernameUsuario", ReplyAction="http://tempuri.org/IUsuario/getByUsernameUsuarioResponse")]
        int getByUsernameUsuario(string username, string passwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/getByUsernameUsuario", ReplyAction="http://tempuri.org/IUsuario/getByUsernameUsuarioResponse")]
        System.Threading.Tasks.Task<int> getByUsernameUsuarioAsync(string username, string passwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/update", ReplyAction="http://tempuri.org/IUsuario/updateResponse")]
        WsSOAP.SOAPService.Usuario update(WsSOAP.SOAPService.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/update", ReplyAction="http://tempuri.org/IUsuario/updateResponse")]
        System.Threading.Tasks.Task<WsSOAP.SOAPService.Usuario> updateAsync(WsSOAP.SOAPService.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/delete", ReplyAction="http://tempuri.org/IUsuario/deleteResponse")]
        void delete(int codUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/delete", ReplyAction="http://tempuri.org/IUsuario/deleteResponse")]
        System.Threading.Tasks.Task deleteAsync(int codUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/create", ReplyAction="http://tempuri.org/IUsuario/createResponse")]
        WsSOAP.SOAPService.Usuario create(WsSOAP.SOAPService.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/create", ReplyAction="http://tempuri.org/IUsuario/createResponse")]
        System.Threading.Tasks.Task<WsSOAP.SOAPService.Usuario> createAsync(WsSOAP.SOAPService.Usuario usuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUsuarioChannel : WsSOAP.SOAPService.IUsuario, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsuarioClient : System.ServiceModel.ClientBase<WsSOAP.SOAPService.IUsuario>, WsSOAP.SOAPService.IUsuario {
        
        public UsuarioClient() {
        }
        
        public UsuarioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsuarioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetVersion() {
            return base.Channel.GetVersion();
        }
        
        public System.Threading.Tasks.Task<string> GetVersionAsync() {
            return base.Channel.GetVersionAsync();
        }
        
        public WsSOAP.SOAPService.Usuario getUsuarioById(int codUsuario) {
            return base.Channel.getUsuarioById(codUsuario);
        }
        
        public System.Threading.Tasks.Task<WsSOAP.SOAPService.Usuario> getUsuarioByIdAsync(int codUsuario) {
            return base.Channel.getUsuarioByIdAsync(codUsuario);
        }
        
        public WsSOAP.SOAPService.Usuario[] getAll() {
            return base.Channel.getAll();
        }
        
        public System.Threading.Tasks.Task<WsSOAP.SOAPService.Usuario[]> getAllAsync() {
            return base.Channel.getAllAsync();
        }
        
        public WsSOAP.SOAPService.Usuario[] getAllNoBorrados() {
            return base.Channel.getAllNoBorrados();
        }
        
        public System.Threading.Tasks.Task<WsSOAP.SOAPService.Usuario[]> getAllNoBorradosAsync() {
            return base.Channel.getAllNoBorradosAsync();
        }
        
        public WsSOAP.SOAPService.Usuario[] getAllBorrados() {
            return base.Channel.getAllBorrados();
        }
        
        public System.Threading.Tasks.Task<WsSOAP.SOAPService.Usuario[]> getAllBorradosAsync() {
            return base.Channel.getAllBorradosAsync();
        }
        
        public int getByUsernameUsuario(string username, string passwd) {
            return base.Channel.getByUsernameUsuario(username, passwd);
        }
        
        public System.Threading.Tasks.Task<int> getByUsernameUsuarioAsync(string username, string passwd) {
            return base.Channel.getByUsernameUsuarioAsync(username, passwd);
        }
        
        public WsSOAP.SOAPService.Usuario update(WsSOAP.SOAPService.Usuario usuario) {
            return base.Channel.update(usuario);
        }
        
        public System.Threading.Tasks.Task<WsSOAP.SOAPService.Usuario> updateAsync(WsSOAP.SOAPService.Usuario usuario) {
            return base.Channel.updateAsync(usuario);
        }
        
        public void delete(int codUsuario) {
            base.Channel.delete(codUsuario);
        }
        
        public System.Threading.Tasks.Task deleteAsync(int codUsuario) {
            return base.Channel.deleteAsync(codUsuario);
        }
        
        public WsSOAP.SOAPService.Usuario create(WsSOAP.SOAPService.Usuario usuario) {
            return base.Channel.create(usuario);
        }
        
        public System.Threading.Tasks.Task<WsSOAP.SOAPService.Usuario> createAsync(WsSOAP.SOAPService.Usuario usuario) {
            return base.Channel.createAsync(usuario);
        }
    }
}
